/// Flutter icons SmileySunglass
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SmileySunglass
///      fonts:
///       - asset: fonts/SmileySunglass.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SmileySunglass {
  SmileySunglass._();

  static const _kFontFam = 'SmileySunglass';

  static const IconData smiling_face_with_sunglasses = const IconData(0xe800, fontFamily: _kFontFam);
}
